In [1]:
import numpy as np

## mathmatical operations

In [4]:
#Create an array of numbers from 1 to 5, and square each number
arr_1= np.arange(1,6)
print(arr_1)
new_arr1= arr_1**2
print(new_arr1)

[1 2 3 4 5]
[ 1  4  9 16 25]


In [6]:
##Given two arrays a = [1, 2, 3] and b = [4, 5, 6], find their element-wise sum and product.

arr_2= np.array([1,2,3] )
arr_3=np.array([4,5,6])
new_arr= arr_2+arr_3
print(new_arr)

[5 7 9]


In [7]:
##Multiply every element of an array by 10.

arr_4= np.array([1,2,3,4,5])
new_arr4= arr_4*10
print(new_arr4)

[10 20 30 40 50]



## statistics and logic


In [ ]:
#Create a random array of 15 integers between 1 and 50, and find:
#Minimum value
#Maximum value
#Mean
#Standard deviation

In [8]:
arr = np.random.randint(1, 50, size=15)
print(arr)

[10 37 36  2 39 45 21 34 45  6 34 15 29 45  7]


In [12]:
maximum= np.max(arr)
print(maximum)
minimum= np.min(arr)
print(minimum)
mean_arr= np.mean(arr)
print(mean)
standard= np.std(arr)
print(standard)

45
2
27.0
14.908610487455451


In [16]:
#From the array [5, 10, 15, 20, 25], find the elements greater than 12.
arr_5=np.array ([5,10,15,20,25])
greater=(arr_5>12)
filtered_elements = arr_5[greater]   # Use boolean indexing to filter
print(filtered_elements)



[15 20 25]


In [20]:
#Count how many elements in a random array are greater than 50.
arr = np.random.randint(1, 100, size=15)
print(arr)
new_arr= arr[arr>50]
print(new_arr.size)

[ 7 46 93 20 67 40 75 65 45 50 83 58 85 53  2]
8
